version: '3'
services:
  jenkins:
    build: ./jenkins/.
    ports:
      - "50000:50000"
      -  "8083:80"
    volumes:
      - $PWD/jenkins/logs:/var/log/jenkins
      - $PWD/jenkins/data:/var/jenkins_home
  nginx:
     build: ./nginx/.
     ports:
      -  "8082:80"
     links:
      -  "jenkins:jenkins"


  